language: go
go:
- 1.10.x
- master
script: make test
notifications:
  slack:
    secure: qQ8MP9uxeR6GWlMIxQMMFAUeZj8k6VptLvGzc9vesPkepzcS1LYK97qu33ZRvf0W8BpVN/Tj8F6lZkKw9NhuVE1CQrXqZpCrBMgzRLfIyGMrWNj+HoIiFeXraiTWTYdfTcXkAYOBrC/7fXqp1GYQsciM1uw66XIsuRkUOxpDzzvm6fdQ89xyJKoplTcUsQLyBhyamwM+G/qu99yUXM5BuEVUB7aZPoK8tAyo0olFg5NyfU+kDjhlA17+H5Kc0owDyA8bcIy0eVZ0tCYQrFcqpl9z8/JnN+lYJRfT59yFZRwzJ07uoO9UCkQh9VylbFrq1C5Kgagiewe0tiDaY3gWe6DUy2c+QAjGyaw7b/7EHz1G/5Fo1K6pkHlVO5buZ64hfphnGJajXYpVWFidmaxsJh7aaUETT3zYRZLzpIdDATuDEmsCMLhNI+8ve6yrwTk1PiriR9Je7tfCvvMc74Wsv4uovThXV/k7EbP03GQtpQnz4/mjGQmURaDB5DD9u8BeeRchhdN6kczg8JZ6kFZwieon+/mpE6a7a9jyAQoZ1BbGugRA0CF5wMlb771Ug8COtFA7LXK9GNbKx+C/dmjfku1ucPfpm6431GYu/hOTm5lF+MXxvuJubRPInrZScIQr6nwTTGbtJdzWsrQGJx567CvL+uriMzwx8ywSF4wJAow=
