// DO NOT EDIT
// This file has been auto-generated by taskhawk-terraform-generator {{GENERATOR_VERSION}}

module "app-dev-myapp" {
  source  = "cloudchacho/taskhawk-queue/google"
  version = "~> {{TFGoogleQueueModuleVersion}}"

  queue = "dev-myapp"

  labels = {
    app = "myapp"
    env = "dev"
  }

  enable_firehose_all_messages = var.enable_firehose_all_messages
}

module "app-dev-secondapp" {
  source  = "cloudchacho/taskhawk-queue/google"
  version = "~> {{TFGoogleQueueModuleVersion}}"

  queue = "dev-secondapp"

  labels = {
    app = "secondapp"
    env = "dev"
  }

  enable_firehose_all_messages = var.enable_firehose_all_messages
}
