// DO NOT EDIT
// This file has been auto-generated by taskhawk-terraform-generator {{GENERATOR_VERSION}}

variable "enable_firehose_all_messages" {
  default = false
  type    = bool
}

variable "enable_alerts" {
  default = false
  type    = bool
}
