// DO NOT EDIT
// This file has been auto-generated by taskhawk-terraform-generator {{GENERATOR_VERSION}}

module "app-dev-anotherapp" {
  source  = "cloudchacho/taskhawk-lambda/aws"
  version = "~> {{TFAWSLambdaModuleVersion}}"

  name          = "dev-anotherapp"
  function_arn  = "arn:aws:lambda:us-west-2:12345:function:myFunction"
  function_name = "myFunction"
}
