// DO NOT EDIT
// This file has been auto-generated by taskhawk-terraform-generator {{GENERATOR_VERSION}}

module "app-dev-myapp" {
  source  = "Automatic/taskhawk-queue/aws"
  version = "~> {{TFAWSQueueModuleVersion}}"

  queue = "DEV-MYAPP"

  tags = {
    App = "myapp"
    Env = "dev"
  }
}
