name: Go tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout PR
        uses: actions/checkout@v2

      - id: setup
        uses: actions/setup-go@v2
        with:
          go-version: '~1.16.0'

      - id: run
        name: Run tests
        run: |
          set -euo pipefail

          go get github.com/go-bindata/go-bindata/...
          go-bindata -prefix "templates/" templates/*
          go get -v ./...
          go get -u github.com/client9/misspell/cmd/misspell
          go get -u honnef.co/go/tools/cmd/staticcheck

          go vet
          go mod tidy
          go mod verify
          misspell -error -locale US *.go
          staticcheck -checks all,-ST1003,-ST1005,-U1000,-SA9002
          ./.gofmt.sh

          make test
        env:
          GO111MODULE: "on"
